### PR TITLE
Team2 - TuND20 - Update core in POM

### PR DESCRIPTION
**Pull request by tund-hcmue**
- web keyword
- BasePage
- BaseTest
- file POM
- Web driver manager (create new file SeleniumDriver.java, Chrome.java)
- Test class for demo navigate to url

### CODE REVIEW

**Review by 18521184 — APPROVED** [review]
Look good bro

**Comment by tandung1710** [comment]
look good but ...

**Comment by phkhuong2** [comment]
good good

**Review by phkhuong2 — APPROVED** [review]
good good

**Review by ToAnhChau — APPROVED** [review]
look good

**Review by haodu1498 — APPROVED** [review]

**Review by DoThiToi — APPROVED** [review]
10 điểm

**Review by tandung1710 — APPROVED** [review]
look good but it's so .... =)))

**Review by SaberEDM — APPROVED** [review]
- Reviewed complete.

**Review by herrynhat — COMMENTED** [review]
Look Good

**Comment by ntmtrang** [comment]
Good

**Review by namnguyen-itvn — APPROVED** [review]
look good, going to merge

**Pull request merged**
