### PR TITLE
Team2-trangntm14-implement-test-case-car-for-sale-search-car-module

### PR DESCRIPTION
**Pull request by ntmtrang**
Create Search Detail Page
Create Car For Sale Page
Create Car For Sale Search Module Test:
- Verify Top Of The Page Section Should Be Displayed Correct When First Time Navigate
- Verify Filter Sort Result Should Be Displayed As Default
- Verify That The Total Number Of Car Item Results In One Page Should Be 25
- Verify That User Can Navigate To Vehicle Detail When Clicking On Car Item
- Verify That Alert Message Should Be Displayed When Searching With Invalid Keyword

### CODE REVIEW

**Comment by ntmtrang** [comment]
@namnguyen-itvn

**Review by herrynhat — APPROVED** [review]
Look good, but why you put declare webElement in function?

**Review by 18521184 — COMMENTED** [review]
Sao ko đặt mấy cái WebElement ở ngoài method luôn để có gì dùng lại

**Comment by ntmtrang** [comment]
> Look good, but why you put declare webElement in function?

Thank for your review, because I was afraid it would be conflict with another. But I have changed my code after thinking again.

**Comment by ntmtrang** [comment]
> Sao ko đặt mấy cái WebElement ở ngoài method luôn để có gì dùng lại

Thank for your review, because I was afraid it would be conflict with another. But I have changed my code after thinking again.

**Pull request closed without merging**
