### PR TITLE
Team 1 NhatNM19 verify that User can do everything

### PR DESCRIPTION
**Pull request by herrynhat**
- [x] 1. > - Create PageObject
- [x] 2. > - Derclare WebElement
- [x] 3. > - Implement function
- [x] 4. > - Implement testcase
- [x] 5. > - Implement Data_**

### CODE REVIEW

**Comment by DoThiToi** [comment]
reviewed

**Comment by herrynhat** [comment]
> reviewed

thanks

**Review by DoThiToi — COMMENTED** [review]
wao

**Comment by herrynhat** [comment]
> wao

Wao gi ma wao, :)

**Pull request closed without merging**
